name: Transporter
main: com.frdfsnlght.transporter.Transporter
version: "9.3"
api-version: 1.15
authors:
  - frdfsnlght
  - Qalthos
website: https://github.com/Parallel-Galaxy/Transporter/
description: >
  Provides teleportation through gates between worlds and servers.
softdepend: [Vault, PermissionsEx]
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /<command> command [<option> ...]
