name: Transporter
main: com.frdfsnlght.transporter.Transporter
version: "9.1"
api-version: 1.13
authors:
  - frdfsnlght
  - Qalthos
website: https://github.com/Qalthos/Transporter/
description: >
  Provides teleportation through gates between worlds and servers.
softdepend: [Vault, PermissionsEx]
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /<command> command [<option> ...]
